### Laboratory Task 5

In [ ]:
# Perform Standard Imports
import torch
import numpy as np
import sys

![My Image](lab5.png)

In [32]:
# Create Function

def set_seed(seed: int) -> None:
    torch.manual_seed(seed)
    np.random.seed(seed)

In [33]:
# Create a Numpy Array

set_seed(42)
arr = np.random.randint(low=0, high=5, size=6)

In [34]:
# Create tensor

x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [43]:
# Change dtype


dt = x.type(torch.int64)
print(dt)
print(dt.dtype)

tensor([3, 4, 2, 4, 4, 1])
torch.int64


In [44]:
# Reshape 

x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [45]:
# Return right hand column

x[:,1]

tensor([1, 3, 5])

In [47]:
# Return a tensor of square values

x_squared = x.pow(2)
print(x_squared)

tensor([[ 0,  1],
        [ 4,  9],
        [16, 25]])


In [53]:
# Create a tensor y

set_seed(42)
y = torch.randint(low=0, high=5, size=(2,3), dtype= torch.int64)
y

tensor([[2, 2, 1],
        [4, 1, 0]])

In [56]:
# Find the Matrix Product of x and y
print(torch.mm(x,y))

tensor([[ 4,  1,  0],
        [16,  7,  2],
        [28, 13,  4]])
